// <auto-generated />
using System;
using Company.Survey.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Company.Survey.Core.Data.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20200614001021_ManyManyClientSurvey")]
    partial class ManyManyClientSurvey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.ClientSurveys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyId1")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SurveyId1", "SurveyVersion");

                    b.ToTable("ClientSurveys");
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StepContentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StepContentId");

                    b.ToTable("Content");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ContentData = "<img src=\\\"/images/databerrymigrationprocess.jpg\\\" alt=\\\"migration process\\\">",
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(5836),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(5866),
                            StepContentId = -1
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplyData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyQuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionId");

                    b.ToTable("Reply");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(9667),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(9680),
                            ReplyData = "e.g. db1",
                            SurveyQuestionId = -15
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(733),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(746),
                            ReplyData = "e.g. AppSI",
                            SurveyQuestionId = -15
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(766),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(769),
                            ReplyData = "e.g. Web01",
                            SurveyQuestionId = -15
                        },
                        new
                        {
                            Id = -4,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(773),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(776),
                            ReplyData = "e.g. DC4",
                            SurveyQuestionId = -15
                        },
                        new
                        {
                            Id = -5,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(780),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(783),
                            ReplyData = "Database",
                            SurveyQuestionId = -16
                        },
                        new
                        {
                            Id = -6,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(787),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(790),
                            ReplyData = "Application",
                            SurveyQuestionId = -16
                        },
                        new
                        {
                            Id = -7,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(794),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(797),
                            ReplyData = "Web",
                            SurveyQuestionId = -16
                        },
                        new
                        {
                            Id = -8,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(801),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(804),
                            ReplyData = "Other",
                            SurveyQuestionId = -16
                        },
                        new
                        {
                            Id = -9,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(807),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(810),
                            ReplyData = "Windows 2016",
                            SurveyQuestionId = -17
                        },
                        new
                        {
                            Id = -10,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(814),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(817),
                            ReplyData = "CentOS v7.2",
                            SurveyQuestionId = -17
                        },
                        new
                        {
                            Id = -11,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(820),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(823),
                            ReplyData = "Redhat v7.0",
                            SurveyQuestionId = -17
                        },
                        new
                        {
                            Id = -12,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(827),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(830),
                            ReplyData = "Windows 2016 DC",
                            SurveyQuestionId = -17
                        },
                        new
                        {
                            Id = -13,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(833),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(836),
                            ReplyData = "500GB C:",
                            SurveyQuestionId = -18
                        },
                        new
                        {
                            Id = -14,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(840),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(843),
                            ReplyData = "700GB's each C: &amp; D: ",
                            SurveyQuestionId = -18
                        },
                        new
                        {
                            Id = -15,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(846),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(850),
                            ReplyData = "1TB F:",
                            SurveyQuestionId = -18
                        },
                        new
                        {
                            Id = -16,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(853),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(856),
                            ReplyData = "2TB each P: &amp; Z:",
                            SurveyQuestionId = -18
                        },
                        new
                        {
                            Id = -17,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(860),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(863),
                            ReplyData = "VM",
                            SurveyQuestionId = -19
                        },
                        new
                        {
                            Id = -18,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(867),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(870),
                            ReplyData = "Physical",
                            SurveyQuestionId = -19
                        },
                        new
                        {
                            Id = -19,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(873),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(876),
                            ReplyData = "VM",
                            SurveyQuestionId = -19
                        },
                        new
                        {
                            Id = -20,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(880),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(884),
                            ReplyData = "Hyper-Visor",
                            SurveyQuestionId = -19
                        },
                        new
                        {
                            Id = -21,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(887),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(890),
                            ReplyData = "e.g. db1",
                            SurveyQuestionId = -20
                        },
                        new
                        {
                            Id = -22,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(894),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(897),
                            ReplyData = "e.g. Web02",
                            SurveyQuestionId = -20
                        },
                        new
                        {
                            Id = -23,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(900),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(903),
                            ReplyData = "MS SQL 2012",
                            SurveyQuestionId = -21
                        },
                        new
                        {
                            Id = -24,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(907),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(910),
                            ReplyData = "MySQL",
                            SurveyQuestionId = -21
                        },
                        new
                        {
                            Id = -25,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(913),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(917),
                            ReplyData = "Sales_DB",
                            SurveyQuestionId = -22
                        },
                        new
                        {
                            Id = -26,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(920),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(923),
                            ReplyData = "Support_DB",
                            SurveyQuestionId = -22
                        },
                        new
                        {
                            Id = -27,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(927),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(930),
                            ReplyData = "C:\\somewhere\\",
                            SurveyQuestionId = -23
                        },
                        new
                        {
                            Id = -28,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(934),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(937),
                            ReplyData = "D:\\somewhere\\",
                            SurveyQuestionId = -23
                        },
                        new
                        {
                            Id = -29,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(940),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(943),
                            ReplyData = "1GB",
                            SurveyQuestionId = -24
                        },
                        new
                        {
                            Id = -30,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(947),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(950),
                            ReplyData = "Physical",
                            SurveyQuestionId = -24
                        },
                        new
                        {
                            Id = -31,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(954),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(957),
                            ReplyData = "e.g. *.mysite.com",
                            SurveyQuestionId = -25
                        },
                        new
                        {
                            Id = -32,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1035),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1038),
                            ReplyData = "e.g. www.mysite.com",
                            SurveyQuestionId = -26
                        },
                        new
                        {
                            Id = -33,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1042),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1045),
                            ReplyData = "Wildcard",
                            SurveyQuestionId = -26
                        },
                        new
                        {
                            Id = -34,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1048),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1051),
                            ReplyData = "single",
                            SurveyQuestionId = -26
                        },
                        new
                        {
                            Id = -35,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1055),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1058),
                            ReplyData = "Web01 C:\\somewhere\\",
                            SurveyQuestionId = -27
                        },
                        new
                        {
                            Id = -36,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1062),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1065),
                            ReplyData = "Web02 D:\\somewhere\\",
                            SurveyQuestionId = -27
                        },
                        new
                        {
                            Id = -37,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1068),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1071),
                            ReplyData = "e.g. www.mysite.com",
                            SurveyQuestionId = -28
                        },
                        new
                        {
                            Id = -38,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1075),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1078),
                            ReplyData = "e.g. my.app.com",
                            SurveyQuestionId = -28
                        },
                        new
                        {
                            Id = -39,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1081),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1084),
                            ReplyData = "Web01 C:\\somewhere\\",
                            SurveyQuestionId = -29
                        },
                        new
                        {
                            Id = -40,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1088),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1091),
                            ReplyData = "Web01 D:\\somewhere\\",
                            SurveyQuestionId = -29
                        },
                        new
                        {
                            Id = -41,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1095),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1098),
                            ReplyData = "e.g. db1",
                            SurveyQuestionId = -30
                        },
                        new
                        {
                            Id = -42,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1101),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1104),
                            ReplyData = "e.g. AppSI",
                            SurveyQuestionId = -30
                        },
                        new
                        {
                            Id = -43,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1108),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1111),
                            ReplyData = "e.g. Web01",
                            SurveyQuestionId = -30
                        },
                        new
                        {
                            Id = -44,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1114),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1118),
                            ReplyData = "e.g. DC4",
                            SurveyQuestionId = -30
                        },
                        new
                        {
                            Id = -45,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1121),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1124),
                            ReplyData = "Database",
                            SurveyQuestionId = -31
                        },
                        new
                        {
                            Id = -46,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1128),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1131),
                            ReplyData = "Application",
                            SurveyQuestionId = -31
                        },
                        new
                        {
                            Id = -47,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1134),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1137),
                            ReplyData = "Web",
                            SurveyQuestionId = -31
                        },
                        new
                        {
                            Id = -48,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1141),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1144),
                            ReplyData = "Other",
                            SurveyQuestionId = -31
                        },
                        new
                        {
                            Id = -49,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1147),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1150),
                            ReplyData = "Windows 2016",
                            SurveyQuestionId = -32
                        },
                        new
                        {
                            Id = -50,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1154),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1157),
                            ReplyData = "CentOS v7.2",
                            SurveyQuestionId = -32
                        },
                        new
                        {
                            Id = -51,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1160),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1163),
                            ReplyData = "Redhat v7.0",
                            SurveyQuestionId = -32
                        },
                        new
                        {
                            Id = -52,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1167),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1170),
                            ReplyData = "Windows 2016 DC",
                            SurveyQuestionId = -32
                        },
                        new
                        {
                            Id = -53,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1173),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1177),
                            ReplyData = "500GB C:",
                            SurveyQuestionId = -33
                        },
                        new
                        {
                            Id = -55,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1180),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1183),
                            ReplyData = "700GB's each C: &amp; D:",
                            SurveyQuestionId = -33
                        },
                        new
                        {
                            Id = -56,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1187),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1190),
                            ReplyData = "1TB F:",
                            SurveyQuestionId = -33
                        },
                        new
                        {
                            Id = -57,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1193),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1196),
                            ReplyData = "2TB each P: &amp; Z:",
                            SurveyQuestionId = -33
                        },
                        new
                        {
                            Id = -58,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1200),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1203),
                            ReplyData = "VM",
                            SurveyQuestionId = -34
                        },
                        new
                        {
                            Id = -59,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1206),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1210),
                            ReplyData = "Physical",
                            SurveyQuestionId = -34
                        },
                        new
                        {
                            Id = -60,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1213),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1216),
                            ReplyData = "VM",
                            SurveyQuestionId = -34
                        },
                        new
                        {
                            Id = -61,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1220),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 121, DateTimeKind.Local).AddTicks(1223),
                            ReplyData = "Hyper-Visor",
                            SurveyQuestionId = -34
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.StepContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyStepId")
                        .IsUnique();

                    b.ToTable("StepContent");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(3271),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(3285),
                            SurveyStepId = -1,
                            Title = "Databerry Migration Process:"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanySite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfQuestionnaire")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "Version");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Version = 8,
                            CompanyName = "Databerry",
                            CompanySite = "www.databerry.com",
                            ContactPhone = "855-350-0707",
                            ContactTitle = "Phone",
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 113, DateTimeKind.Local).AddTicks(7918),
                            DateOfQuestionnaire = new DateTime(2020, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsComplete = false,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 116, DateTimeKind.Local).AddTicks(7934),
                            RequestedEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Infrastructure Migration Survey Form V8"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Quesiton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SurveyQuestionGroupID")
                        .HasColumnType("int");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionGroupID");

                    b.HasIndex("SurveyStepId");

                    b.ToTable("SurveyQuestion");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(4969),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(4984),
                            Note = "(e.g. Amazon AWS, Azure, On-Premise)",
                            Order = 0,
                            Quesiton = "Current Hosting Service Provider?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7771),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7787),
                            Note = "",
                            Order = 2,
                            Quesiton = "Total count of Server(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7846),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7850),
                            Note = "",
                            Order = 3,
                            Quesiton = "Is there a SAN? (Yes or No)",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -4,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7854),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7858),
                            Note = "",
                            Order = 5,
                            Quesiton = "Total Count of Database(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -5,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7862),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7865),
                            Note = "(e.g. .NET 4.5 | PHP 5.4 | Java 1.5)",
                            Order = 6,
                            Quesiton = "Custom Applications, Applications, Frameworks, | Versions? Please list all Applications types/versions &amp; Names ?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -6,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7869),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7872),
                            Note = "(e.g. Joomla 2.x, Drupal 7.2, WordPress 4.1, QuickBooks v18.0 etc.)",
                            Order = 6,
                            Quesiton = "Are there any Third-party commercial applications or platforms | API’s | Plug-ins?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -7,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7931),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7934),
                            Note = "(Note: VPN will be required if migrating over WAN)",
                            Order = 7,
                            Quesiton = "Active Directory Migration (Yes or No)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -8,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7939),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7942),
                            Note = "(e.g. iOS Apple swift, Android java, Windows Mobile)",
                            Order = 8,
                            Quesiton = "Are there any Mobile Apps?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -9,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7946),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7949),
                            Note = "(e.g. Authorize.net, PayPal, Stripe, Magento etc.)",
                            Order = 9,
                            Quesiton = "Are there any E-commerce or Payment Gateways Service/platforms involved?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -10,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7953),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7956),
                            Order = 11,
                            Quesiton = "Total SSL Certificate(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -11,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7960),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7963),
                            Note = "(e.g. Webmin v1.89, Plesk v12.5, CPanel v58, Docker v17.x)",
                            Order = 12,
                            Quesiton = "Is there any Server Control Panels installed?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -12,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7966),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7970),
                            Note = "(e.g. IIS 7.0, Apache 2.2, Nginx 1.1)",
                            Order = 14,
                            Quesiton = "List existing Web Server platform &amp; Versions?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -13,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7973),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7977),
                            Note = "(e.g. Sendmail v8.7, PHPmailer, Postfix, MS Exchange v2013, Exim)",
                            Order = 14,
                            Quesiton = "Are there any E-mail platforms or services installed on the Server(s) Type | Version?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -14,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7980),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7983),
                            Note = "(e.g. Google analytics data and/or Environment estimated usage of High, Medium, Low)",
                            Order = 15,
                            Quesiton = "Total Monthly estimated average of Usage Traffic and/or Transactions volume?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -15,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7987),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(7990),
                            Order = 0,
                            Quesiton = "Name of Server",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -16,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8608),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8621),
                            Order = 1,
                            Quesiton = "Describe the Type of Server",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -17,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8644),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8647),
                            Order = 2,
                            Quesiton = "OS Type & Version",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -18,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8651),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8654),
                            Order = 3,
                            Quesiton = "Total Storage of Server in (GB'S TB'S) & amp; Partitions",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -19,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8658),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8661),
                            Order = 4,
                            Quesiton = "State of Server (Physical, Virtual, Hyper-Visor)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -20,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8666),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8669),
                            Order = 0,
                            Quesiton = "DB Server Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -21,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8673),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8676),
                            Order = 1,
                            Quesiton = "DB Engine Type &amp; Version",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -22,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8680),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8683),
                            Order = 2,
                            Quesiton = "DB Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -23,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8687),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8690),
                            Order = 3,
                            Quesiton = "DB Location",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -24,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8694),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8697),
                            Order = 4,
                            Quesiton = "Total DB Size in (MB's GB'S TB'S)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -25,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8701),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8704),
                            Order = 0,
                            Quesiton = "SSL Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -26,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8708),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8711),
                            Order = 1,
                            Quesiton = "SSL Type",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -27,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8715),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8718),
                            Order = 2,
                            Quesiton = "SSL Location (Server Name/Location)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -28,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8722),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8725),
                            Order = 0,
                            Quesiton = "Website Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -4,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -29,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8729),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8732),
                            Order = 1,
                            Quesiton = "Website Location (Server Name/Location)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -4,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -30,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8736),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8739),
                            Order = 0,
                            Quesiton = "Name of Server",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -31,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8742),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8745),
                            Order = 1,
                            Quesiton = "Describe the Type of Server",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -32,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8749),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8752),
                            Order = 2,
                            Quesiton = "OS Type & Version",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -33,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8756),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8759),
                            Order = 3,
                            Quesiton = "Total Storage of Server in (GB'S TB'S) & amp; Partitions",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -34,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8763),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8766),
                            Order = 4,
                            Quesiton = "State of Server (Physical, Virtual, Hyper-Visor)",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -35,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8769),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8772),
                            Note = "(e.g. Amazon AWS, Azure, On-Premise)",
                            Order = 0,
                            Quesiton = "Moving to Hosting Service Provider?",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -36,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8776),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8780),
                            Order = 2,
                            Quesiton = "Is there a SAN? (Yes or No)",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -37,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8783),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8786),
                            Note = "(e.g. P= Physical V=Virtual P-P, P-V, V-V, V-P)",
                            Order = 3,
                            Quesiton = "Specify the Type of Migration?",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -38,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8790),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(8793),
                            Order = 4,
                            Quesiton = "Please include any additional technical details that you may feel is important that was not covered above:",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyStepId");

                    b.ToTable("SurveyQuestionGroup");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(335),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(377),
                            Order = 1,
                            SurveyStepId = -2,
                            Title = "Specify the number of Source Server(s) to be migrated, Type, OS, Storage, State?"
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(3156),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(3176),
                            Note = "(e.g. Microsoft SQL 2014, MariaDB 5.6, MySQL 5.4, Name of DB, size of DB, MB’s, GB’s, TB’s)",
                            Order = 4,
                            SurveyStepId = -2,
                            Title = "Specify the Database Engine Server(s) Type | Version | Name | Size | Quantity?"
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(3844),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(3857),
                            Note = "(if Yes please List)",
                            Order = 10,
                            SurveyStepId = -2,
                            Title = "Are there any SSL certificate(s) installed (Type &amp; Location If possible)?"
                        },
                        new
                        {
                            Id = -4,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(3879),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(3882),
                            Order = 13,
                            SurveyStepId = -2,
                            Title = "List the number of Website Names (&amp; Location on Servers if possible)?"
                        },
                        new
                        {
                            Id = -5,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(4099),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 120, DateTimeKind.Local).AddTicks(4105),
                            Order = 1,
                            SurveyStepId = -3,
                            Title = "Specify the number of Source Server(s) to be migrated, Type, OS, Storage, State?"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyId1")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyVersion")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId1", "SurveyVersion");

                    b.ToTable("SurveyStep");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 118, DateTimeKind.Local).AddTicks(9975),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(7),
                            Order = 0,
                            SurveyId = -1,
                            Title = "Organization/Company &amp; Primary Contact Details: Step A"
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(2170),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(2188),
                            Order = 1,
                            SurveyId = -1,
                            Title = "Source Migration Infrastructure Details: Step B"
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(2223),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 13, 20, 10, 20, 119, DateTimeKind.Local).AddTicks(2226),
                            Order = 2,
                            SurveyId = -1,
                            Title = "Destination Migration Infrastructure Details: Step C"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.ClientSurveys", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.Client", "Client")
                        .WithMany("ClientSurveys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Survey.Core.Data.Entities.Survey", "Survey")
                        .WithMany("ClientSurveys")
                        .HasForeignKey("SurveyId1", "SurveyVersion");
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Content", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.StepContent", "StepContent")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("StepContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Reply", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyQuestion", "SurveyQuestion")
                        .WithMany("PossibleReplies")
                        .HasForeignKey("SurveyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.StepContent", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithOne("StepContent")
                        .HasForeignKey("Company.Survey.Core.Data.Entities.StepContent", "SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", "SurveyQuestionGroup")
                        .WithMany("SurveyGroupQuestions")
                        .HasForeignKey("SurveyQuestionGroupID");

                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyStep", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.Survey", "Survey")
                        .WithMany("SurveySteps")
                        .HasForeignKey("SurveyId1", "SurveyVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
