// <auto-generated />
using System;
using Company.Survey.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Company.Survey.Core.Data.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20200614051205_ClientSurveySeed")]
    partial class ClientSurveySeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CompanyName = "Test Company",
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 312, DateTimeKind.Local).AddTicks(7548),
                            Email = "joneszj@gmail.com",
                            FirstName = "Zachary",
                            IsActive = true,
                            LastName = "Jones",
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 315, DateTimeKind.Local).AddTicks(8236),
                            Phone = "555-333-1111"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.ClientSurveys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientSurveyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SurveyId");

                    b.ToTable("ClientSurveys");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ClientId = -1,
                            ClientSurveyKey = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 317, DateTimeKind.Local).AddTicks(2634),
                            IsActive = true,
                            IsComplete = false,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 317, DateTimeKind.Local).AddTicks(2678),
                            RequestedEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequestedStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SurveyId = -1
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StepContentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StepContentId");

                    b.ToTable("Content");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ContentData = "<img src=\\\"/images/databerrymigrationprocess.jpg\\\" alt=\\\"migration process\\\">",
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 321, DateTimeKind.Local).AddTicks(9091),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 321, DateTimeKind.Local).AddTicks(9120),
                            StepContentId = -1
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientSurveyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplyData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyQuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientSurveyId");

                    b.HasIndex("SurveyQuestionId");

                    b.ToTable("Reply");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(7909),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(7926),
                            ReplyData = "e.g. db1",
                            SurveyQuestionId = -15
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9295),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9311),
                            ReplyData = "e.g. AppSI",
                            SurveyQuestionId = -15
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9332),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9336),
                            ReplyData = "e.g. Web01",
                            SurveyQuestionId = -15
                        },
                        new
                        {
                            Id = -4,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9340),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9343),
                            ReplyData = "e.g. DC4",
                            SurveyQuestionId = -15
                        },
                        new
                        {
                            Id = -5,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9347),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9351),
                            ReplyData = "Database",
                            SurveyQuestionId = -16
                        },
                        new
                        {
                            Id = -6,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9355),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9358),
                            ReplyData = "Application",
                            SurveyQuestionId = -16
                        },
                        new
                        {
                            Id = -7,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9364),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9367),
                            ReplyData = "Web",
                            SurveyQuestionId = -16
                        },
                        new
                        {
                            Id = -8,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9371),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9375),
                            ReplyData = "Other",
                            SurveyQuestionId = -16
                        },
                        new
                        {
                            Id = -9,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9379),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9382),
                            ReplyData = "Windows 2016",
                            SurveyQuestionId = -17
                        },
                        new
                        {
                            Id = -10,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9386),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9390),
                            ReplyData = "CentOS v7.2",
                            SurveyQuestionId = -17
                        },
                        new
                        {
                            Id = -11,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9394),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9397),
                            ReplyData = "Redhat v7.0",
                            SurveyQuestionId = -17
                        },
                        new
                        {
                            Id = -12,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9402),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9405),
                            ReplyData = "Windows 2016 DC",
                            SurveyQuestionId = -17
                        },
                        new
                        {
                            Id = -13,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9409),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9412),
                            ReplyData = "500GB C:",
                            SurveyQuestionId = -18
                        },
                        new
                        {
                            Id = -14,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9416),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9420),
                            ReplyData = "700GB's each C: &amp; D: ",
                            SurveyQuestionId = -18
                        },
                        new
                        {
                            Id = -15,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9424),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9427),
                            ReplyData = "1TB F:",
                            SurveyQuestionId = -18
                        },
                        new
                        {
                            Id = -16,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9431),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9435),
                            ReplyData = "2TB each P: &amp; Z:",
                            SurveyQuestionId = -18
                        },
                        new
                        {
                            Id = -17,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9439),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9442),
                            ReplyData = "VM",
                            SurveyQuestionId = -19
                        },
                        new
                        {
                            Id = -18,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9446),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9450),
                            ReplyData = "Physical",
                            SurveyQuestionId = -19
                        },
                        new
                        {
                            Id = -19,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9454),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9457),
                            ReplyData = "VM",
                            SurveyQuestionId = -19
                        },
                        new
                        {
                            Id = -20,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9461),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9464),
                            ReplyData = "Hyper-Visor",
                            SurveyQuestionId = -19
                        },
                        new
                        {
                            Id = -21,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9468),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9472),
                            ReplyData = "e.g. db1",
                            SurveyQuestionId = -20
                        },
                        new
                        {
                            Id = -22,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9476),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9479),
                            ReplyData = "e.g. Web02",
                            SurveyQuestionId = -20
                        },
                        new
                        {
                            Id = -23,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9483),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9486),
                            ReplyData = "MS SQL 2012",
                            SurveyQuestionId = -21
                        },
                        new
                        {
                            Id = -24,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9490),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9494),
                            ReplyData = "MySQL",
                            SurveyQuestionId = -21
                        },
                        new
                        {
                            Id = -25,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9497),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9501),
                            ReplyData = "Sales_DB",
                            SurveyQuestionId = -22
                        },
                        new
                        {
                            Id = -26,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9505),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9508),
                            ReplyData = "Support_DB",
                            SurveyQuestionId = -22
                        },
                        new
                        {
                            Id = -27,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9512),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9515),
                            ReplyData = "C:\\somewhere\\",
                            SurveyQuestionId = -23
                        },
                        new
                        {
                            Id = -28,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9519),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9523),
                            ReplyData = "D:\\somewhere\\",
                            SurveyQuestionId = -23
                        },
                        new
                        {
                            Id = -29,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9527),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9530),
                            ReplyData = "1GB",
                            SurveyQuestionId = -24
                        },
                        new
                        {
                            Id = -30,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9534),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9538),
                            ReplyData = "Physical",
                            SurveyQuestionId = -24
                        },
                        new
                        {
                            Id = -31,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9542),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9545),
                            ReplyData = "e.g. *.mysite.com",
                            SurveyQuestionId = -25
                        },
                        new
                        {
                            Id = -32,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9549),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9552),
                            ReplyData = "e.g. www.mysite.com",
                            SurveyQuestionId = -26
                        },
                        new
                        {
                            Id = -33,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9556),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9560),
                            ReplyData = "Wildcard",
                            SurveyQuestionId = -26
                        },
                        new
                        {
                            Id = -34,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9564),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9567),
                            ReplyData = "single",
                            SurveyQuestionId = -26
                        },
                        new
                        {
                            Id = -35,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9571),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9574),
                            ReplyData = "Web01 C:\\somewhere\\",
                            SurveyQuestionId = -27
                        },
                        new
                        {
                            Id = -36,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9580),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9583),
                            ReplyData = "Web02 D:\\somewhere\\",
                            SurveyQuestionId = -27
                        },
                        new
                        {
                            Id = -37,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9587),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9591),
                            ReplyData = "e.g. www.mysite.com",
                            SurveyQuestionId = -28
                        },
                        new
                        {
                            Id = -38,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9594),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9598),
                            ReplyData = "e.g. my.app.com",
                            SurveyQuestionId = -28
                        },
                        new
                        {
                            Id = -39,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9602),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9605),
                            ReplyData = "Web01 C:\\somewhere\\",
                            SurveyQuestionId = -29
                        },
                        new
                        {
                            Id = -40,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9609),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9612),
                            ReplyData = "Web01 D:\\somewhere\\",
                            SurveyQuestionId = -29
                        },
                        new
                        {
                            Id = -41,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9616),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9620),
                            ReplyData = "e.g. db1",
                            SurveyQuestionId = -30
                        },
                        new
                        {
                            Id = -42,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9623),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9627),
                            ReplyData = "e.g. AppSI",
                            SurveyQuestionId = -30
                        },
                        new
                        {
                            Id = -43,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9631),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9634),
                            ReplyData = "e.g. Web01",
                            SurveyQuestionId = -30
                        },
                        new
                        {
                            Id = -44,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9638),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9641),
                            ReplyData = "e.g. DC4",
                            SurveyQuestionId = -30
                        },
                        new
                        {
                            Id = -45,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9645),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9649),
                            ReplyData = "Database",
                            SurveyQuestionId = -31
                        },
                        new
                        {
                            Id = -46,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9652),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9656),
                            ReplyData = "Application",
                            SurveyQuestionId = -31
                        },
                        new
                        {
                            Id = -47,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9660),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9663),
                            ReplyData = "Web",
                            SurveyQuestionId = -31
                        },
                        new
                        {
                            Id = -48,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9667),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9670),
                            ReplyData = "Other",
                            SurveyQuestionId = -31
                        },
                        new
                        {
                            Id = -49,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9674),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9678),
                            ReplyData = "Windows 2016",
                            SurveyQuestionId = -32
                        },
                        new
                        {
                            Id = -50,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9682),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9685),
                            ReplyData = "CentOS v7.2",
                            SurveyQuestionId = -32
                        },
                        new
                        {
                            Id = -51,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9689),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9692),
                            ReplyData = "Redhat v7.0",
                            SurveyQuestionId = -32
                        },
                        new
                        {
                            Id = -52,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9696),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9700),
                            ReplyData = "Windows 2016 DC",
                            SurveyQuestionId = -32
                        },
                        new
                        {
                            Id = -53,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9703),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9707),
                            ReplyData = "500GB C:",
                            SurveyQuestionId = -33
                        },
                        new
                        {
                            Id = -55,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9711),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9714),
                            ReplyData = "700GB's each C: &amp; D:",
                            SurveyQuestionId = -33
                        },
                        new
                        {
                            Id = -56,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9783),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9787),
                            ReplyData = "1TB F:",
                            SurveyQuestionId = -33
                        },
                        new
                        {
                            Id = -57,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9791),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9794),
                            ReplyData = "2TB each P: &amp; Z:",
                            SurveyQuestionId = -33
                        },
                        new
                        {
                            Id = -58,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9798),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9802),
                            ReplyData = "VM",
                            SurveyQuestionId = -34
                        },
                        new
                        {
                            Id = -59,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9805),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9809),
                            ReplyData = "Physical",
                            SurveyQuestionId = -34
                        },
                        new
                        {
                            Id = -60,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9813),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9816),
                            ReplyData = "VM",
                            SurveyQuestionId = -34
                        },
                        new
                        {
                            Id = -61,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9820),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(9824),
                            ReplyData = "Hyper-Visor",
                            SurveyQuestionId = -34
                        },
                        new
                        {
                            Id = -62,
                            ClientSurveyId = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 324, DateTimeKind.Local).AddTicks(438),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 324, DateTimeKind.Local).AddTicks(454),
                            ReplyData = "Azure",
                            SurveyQuestionId = -1
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.StepContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyStepId")
                        .IsUnique();

                    b.ToTable("StepContent");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 321, DateTimeKind.Local).AddTicks(5578),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 321, DateTimeKind.Local).AddTicks(5607),
                            SurveyStepId = -1,
                            Title = "Databerry Migration Process:"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanySite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfQuestionnaire")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuveryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuveryId", "Version")
                        .IsUnique();

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CompanyName = "Databerry",
                            CompanySite = "www.databerry.com",
                            ContactPhone = "855-350-0707",
                            ContactTitle = "Phone",
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 317, DateTimeKind.Local).AddTicks(7262),
                            DateOfQuestionnaire = new DateTime(2020, 6, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 317, DateTimeKind.Local).AddTicks(7293),
                            SuveryId = -1,
                            Title = "Infrastructure Migration Survey Form V8",
                            Version = 8
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Quesiton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SurveyQuestionGroupID")
                        .HasColumnType("int");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionGroupID");

                    b.HasIndex("SurveyStepId");

                    b.ToTable("SurveyQuestion");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(410),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(437),
                            Note = "(e.g. Amazon AWS, Azure, On-Premise)",
                            Order = 0,
                            Quesiton = "Current Hosting Service Provider?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5537),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5559),
                            Note = "",
                            Order = 2,
                            Quesiton = "Total count of Server(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5623),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5628),
                            Note = "",
                            Order = 3,
                            Quesiton = "Is there a SAN? (Yes or No)",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -4,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5632),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5636),
                            Note = "",
                            Order = 5,
                            Quesiton = "Total Count of Database(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -5,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5640),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5644),
                            Note = "(e.g. .NET 4.5 | PHP 5.4 | Java 1.5)",
                            Order = 6,
                            Quesiton = "Custom Applications, Applications, Frameworks, | Versions? Please list all Applications types/versions &amp; Names ?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -6,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5649),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5652),
                            Note = "(e.g. Joomla 2.x, Drupal 7.2, WordPress 4.1, QuickBooks v18.0 etc.)",
                            Order = 6,
                            Quesiton = "Are there any Third-party commercial applications or platforms | API’s | Plug-ins?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -7,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5656),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5660),
                            Note = "(Note: VPN will be required if migrating over WAN)",
                            Order = 7,
                            Quesiton = "Active Directory Migration (Yes or No)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -8,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5664),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5667),
                            Note = "(e.g. iOS Apple swift, Android java, Windows Mobile)",
                            Order = 8,
                            Quesiton = "Are there any Mobile Apps?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -9,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5672),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5675),
                            Note = "(e.g. Authorize.net, PayPal, Stripe, Magento etc.)",
                            Order = 9,
                            Quesiton = "Are there any E-commerce or Payment Gateways Service/platforms involved?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -10,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5679),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5683),
                            Order = 11,
                            Quesiton = "Total SSL Certificate(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -11,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5687),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5690),
                            Note = "(e.g. Webmin v1.89, Plesk v12.5, CPanel v58, Docker v17.x)",
                            Order = 12,
                            Quesiton = "Is there any Server Control Panels installed?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -12,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5694),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5698),
                            Note = "(e.g. IIS 7.0, Apache 2.2, Nginx 1.1)",
                            Order = 14,
                            Quesiton = "List existing Web Server platform &amp; Versions?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -13,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5702),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5705),
                            Note = "(e.g. Sendmail v8.7, PHPmailer, Postfix, MS Exchange v2013, Exim)",
                            Order = 14,
                            Quesiton = "Are there any E-mail platforms or services installed on the Server(s) Type | Version?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -14,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5710),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5713),
                            Note = "(e.g. Google analytics data and/or Environment estimated usage of High, Medium, Low)",
                            Order = 15,
                            Quesiton = "Total Monthly estimated average of Usage Traffic and/or Transactions volume?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -15,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5718),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(5721),
                            Order = 0,
                            Quesiton = "Name of Server",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -16,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6524),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6540),
                            Order = 1,
                            Quesiton = "Describe the Type of Server",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -17,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6566),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6570),
                            Order = 2,
                            Quesiton = "OS Type & Version",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -18,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6574),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6577),
                            Order = 3,
                            Quesiton = "Total Storage of Server in (GB'S TB'S) & amp; Partitions",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -19,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6581),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6585),
                            Order = 4,
                            Quesiton = "State of Server (Physical, Virtual, Hyper-Visor)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -20,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6589),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6593),
                            Order = 0,
                            Quesiton = "DB Server Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -21,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6597),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6600),
                            Order = 1,
                            Quesiton = "DB Engine Type &amp; Version",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -22,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6606),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6609),
                            Order = 2,
                            Quesiton = "DB Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -23,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6614),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6617),
                            Order = 3,
                            Quesiton = "DB Location",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -24,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6621),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6625),
                            Order = 4,
                            Quesiton = "Total DB Size in (MB's GB'S TB'S)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -25,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6629),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6632),
                            Order = 0,
                            Quesiton = "SSL Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -26,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6636),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6640),
                            Order = 1,
                            Quesiton = "SSL Type",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -27,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6644),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6648),
                            Order = 2,
                            Quesiton = "SSL Location (Server Name/Location)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -28,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6652),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6655),
                            Order = 0,
                            Quesiton = "Website Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -4,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -29,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6746),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6751),
                            Order = 1,
                            Quesiton = "Website Location (Server Name/Location)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -4,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -30,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6755),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6759),
                            Order = 0,
                            Quesiton = "Name of Server",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -31,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6763),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6766),
                            Order = 1,
                            Quesiton = "Describe the Type of Server",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -32,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6770),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6774),
                            Order = 2,
                            Quesiton = "OS Type & Version",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -33,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6778),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6781),
                            Order = 3,
                            Quesiton = "Total Storage of Server in (GB'S TB'S) & amp; Partitions",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -34,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6785),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6789),
                            Order = 4,
                            Quesiton = "State of Server (Physical, Virtual, Hyper-Visor)",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -35,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6793),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6796),
                            Note = "(e.g. Amazon AWS, Azure, On-Premise)",
                            Order = 0,
                            Quesiton = "Moving to Hosting Service Provider?",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -36,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6801),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6804),
                            Order = 2,
                            Quesiton = "Is there a SAN? (Yes or No)",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -37,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6808),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6811),
                            Note = "(e.g. P= Physical V=Virtual P-P, P-V, V-V, V-P)",
                            Order = 3,
                            Quesiton = "Specify the Type of Migration?",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -38,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6815),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 323, DateTimeKind.Local).AddTicks(6819),
                            Order = 4,
                            Quesiton = "Please include any additional technical details that you may feel is important that was not covered above:",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyStepId");

                    b.ToTable("SurveyQuestionGroup");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(3263),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(3301),
                            Order = 1,
                            SurveyStepId = -2,
                            Title = "Specify the number of Source Server(s) to be migrated, Type, OS, Storage, State?"
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(7385),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(7417),
                            Note = "(e.g. Microsoft SQL 2014, MariaDB 5.6, MySQL 5.4, Name of DB, size of DB, MB’s, GB’s, TB’s)",
                            Order = 4,
                            SurveyStepId = -2,
                            Title = "Specify the Database Engine Server(s) Type | Version | Name | Size | Quantity?"
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(8607),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(8633),
                            Note = "(if Yes please List)",
                            Order = 10,
                            SurveyStepId = -2,
                            Title = "Are there any SSL certificate(s) installed (Type &amp; Location If possible)?"
                        },
                        new
                        {
                            Id = -4,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(8688),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(8705),
                            Order = 13,
                            SurveyStepId = -2,
                            Title = "List the number of Website Names (&amp; Location on Servers if possible)?"
                        },
                        new
                        {
                            Id = -5,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(9140),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 322, DateTimeKind.Local).AddTicks(9162),
                            Order = 1,
                            SurveyStepId = -3,
                            Title = "Specify the number of Source Server(s) to be migrated, Type, OS, Storage, State?"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyVersion")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId", "SurveyVersion");

                    b.ToTable("SurveyStep");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 320, DateTimeKind.Local).AddTicks(9092),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 320, DateTimeKind.Local).AddTicks(9122),
                            Order = 0,
                            SurveyId = -1,
                            SurveyVersion = 8,
                            Title = "Organization/Company &amp; Primary Contact Details: Step A"
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 321, DateTimeKind.Local).AddTicks(3625),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 321, DateTimeKind.Local).AddTicks(3662),
                            Order = 1,
                            SurveyId = -1,
                            SurveyVersion = 8,
                            Title = "Source Migration Infrastructure Details: Step B"
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 14, 1, 12, 4, 321, DateTimeKind.Local).AddTicks(3767),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 14, 1, 12, 4, 321, DateTimeKind.Local).AddTicks(3786),
                            Order = 2,
                            SurveyId = -1,
                            SurveyVersion = 8,
                            Title = "Destination Migration Infrastructure Details: Step C"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.ClientSurveys", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.Client", "Client")
                        .WithMany("ClientSurveys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Survey.Core.Data.Entities.Survey", "Survey")
                        .WithMany("ClientSurveys")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Content", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.StepContent", "StepContent")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("StepContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Reply", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.ClientSurveys", "ClientSurvey")
                        .WithMany("ClientQuestionReplies")
                        .HasForeignKey("ClientSurveyId");

                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyQuestion", "SurveyQuestion")
                        .WithMany("PossibleReplies")
                        .HasForeignKey("SurveyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.StepContent", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithOne("StepContent")
                        .HasForeignKey("Company.Survey.Core.Data.Entities.StepContent", "SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", "SurveyQuestionGroup")
                        .WithMany("SurveyGroupQuestions")
                        .HasForeignKey("SurveyQuestionGroupID");

                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyStep", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.Survey", "Survey")
                        .WithMany("SurveySteps")
                        .HasForeignKey("SurveyId", "SurveyVersion")
                        .HasPrincipalKey("SuveryId", "Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
