// <auto-generated />
using System;
using Company.Survey.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Company.Survey.Core.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20200617163805_Attempt ClientSurveys Seed")]
    partial class AttemptClientSurveysSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CompanyName = "Test Company",
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 234, DateTimeKind.Local).AddTicks(6934),
                            Email = "joneszj@gmail.com",
                            FirstName = "Zachary",
                            IsActive = true,
                            LastName = "Jones",
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 234, DateTimeKind.Local).AddTicks(6977),
                            Phone = "555-333-1111"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.ClientSurveys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientSurveyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SurveyId");

                    b.ToTable("ClientSurveys");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ClientId = -1,
                            ClientSurveyKey = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(6228),
                            IsActive = true,
                            IsComplete = false,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(6243),
                            SurveyId = -1
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StepContentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StepContentId");

                    b.ToTable("Content");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ContentData = "<img class=\"img-fluid\" src=\"/assets/images/databerrymigrationprocess.jpg\" alt=\"migration process\">",
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(6308),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(6324),
                            StepContentId = -1
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientSurveyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplyData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyQuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientSurveyId");

                    b.HasIndex("SurveyQuestionId");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.StepContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyStepId")
                        .IsUnique();

                    b.ToTable("StepContent");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(4057),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(4072),
                            SurveyStepId = -1,
                            Title = "Databerry Migration Process:"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanySite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfQuestionnaire")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Version")
                        .IsUnique();

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CompanyName = "Databerry",
                            CompanySite = "www.databerry.com",
                            ContactPhone = "855-350-0707",
                            ContactTitle = "Phone",
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 226, DateTimeKind.Local).AddTicks(3551),
                            DateOfQuestionnaire = new DateTime(2020, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 229, DateTimeKind.Local).AddTicks(3991),
                            Title = "Infrastructure Migration Survey Form V8",
                            Version = 8
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Quesiton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SurveyQuestionGroupID")
                        .HasColumnType("int");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyQuestionGroupID");

                    b.HasIndex("SurveyStepId");

                    b.ToTable("SurveyQuestion");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(1586),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(1601),
                            Note = "(e.g. Amazon AWS, Azure, On-Premise)",
                            Order = 0,
                            Quesiton = "Current Hosting Service Provider?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4202),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4217),
                            Note = "",
                            Order = 2,
                            Quesiton = "Total count of Server(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4279),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4283),
                            Note = "",
                            Order = 3,
                            Quesiton = "Is there a SAN? (Yes or No)",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -4,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4287),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4290),
                            Note = "",
                            Order = 5,
                            Quesiton = "Total Count of Database(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -5,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4294),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4298),
                            Note = "(e.g. .NET 4.5 | PHP 5.4 | Java 1.5)",
                            Order = 6,
                            Quesiton = "Custom Applications, Applications, Frameworks, | Versions? Please list all Applications types/versions &amp; Names ?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -6,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4302),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4305),
                            Note = "(e.g. Joomla 2.x, Drupal 7.2, WordPress 4.1, QuickBooks v18.0 etc.)",
                            Order = 6,
                            Quesiton = "Are there any Third-party commercial applications or platforms | API’s | Plug-ins?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -7,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4309),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4313),
                            Note = "(Note: VPN will be required if migrating over WAN)",
                            Order = 7,
                            Quesiton = "Active Directory Migration (Yes or No)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -8,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4318),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4322),
                            Note = "(e.g. iOS Apple swift, Android java, Windows Mobile)",
                            Order = 8,
                            Quesiton = "Are there any Mobile Apps?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -9,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4326),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4329),
                            Note = "(e.g. Authorize.net, PayPal, Stripe, Magento etc.)",
                            Order = 9,
                            Quesiton = "Are there any E-commerce or Payment Gateways Service/platforms involved?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -10,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4333),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4337),
                            Order = 11,
                            Quesiton = "Total SSL Certificate(s)?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -11,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4341),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4345),
                            Note = "(e.g. Webmin v1.89, Plesk v12.5, CPanel v58, Docker v17.x)",
                            Order = 12,
                            Quesiton = "Is there any Server Control Panels installed?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -12,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4349),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4352),
                            Note = "(e.g. IIS 7.0, Apache 2.2, Nginx 1.1)",
                            Order = 14,
                            Quesiton = "List existing Web Server platform &amp; Versions?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -13,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4356),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4359),
                            Note = "(e.g. Sendmail v8.7, PHPmailer, Postfix, MS Exchange v2013, Exim)",
                            Order = 14,
                            Quesiton = "Are there any E-mail platforms or services installed on the Server(s) Type | Version?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -14,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4363),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4367),
                            Note = "(e.g. Google analytics data and/or Environment estimated usage of High, Medium, Low)",
                            Order = 15,
                            Quesiton = "Total Monthly estimated average of Usage Traffic and/or Transactions volume?",
                            ReplyType = "Text",
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -15,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4370),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(4374),
                            Order = 0,
                            Quesiton = "Name of Server",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -16,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5000),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5014),
                            Order = 1,
                            Quesiton = "Describe the Type of Server",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -17,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5036),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5039),
                            Order = 2,
                            Quesiton = "OS Type & Version",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -18,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5043),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5047),
                            Order = 3,
                            Quesiton = "Total Storage of Server in (GB'S TB'S) & amp; Partitions",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -19,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5051),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5055),
                            Order = 4,
                            Quesiton = "State of Server (Physical, Virtual, Hyper-Visor)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -1,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -20,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5059),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5062),
                            Order = 0,
                            Quesiton = "DB Server Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -21,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5066),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5069),
                            Order = 1,
                            Quesiton = "DB Engine Type &amp; Version",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -22,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5073),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5077),
                            Order = 2,
                            Quesiton = "DB Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -23,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5081),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5084),
                            Order = 3,
                            Quesiton = "DB Location",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -24,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5088),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5092),
                            Order = 4,
                            Quesiton = "Total DB Size in (MB's GB'S TB'S)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -2,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -25,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5096),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5099),
                            Order = 0,
                            Quesiton = "SSL Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -26,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5160),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5164),
                            Order = 1,
                            Quesiton = "SSL Type",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -27,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5169),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5173),
                            Order = 2,
                            Quesiton = "SSL Location (Server Name/Location)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -3,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -28,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5177),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5180),
                            Order = 0,
                            Quesiton = "Website Name",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -4,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -29,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5184),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5188),
                            Order = 1,
                            Quesiton = "Website Location (Server Name/Location)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -4,
                            SurveyStepId = -2
                        },
                        new
                        {
                            Id = -30,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5192),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5195),
                            Order = 0,
                            Quesiton = "Name of Server",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -5,
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -31,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5199),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5202),
                            Order = 1,
                            Quesiton = "Describe the Type of Server",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -5,
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -32,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5206),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5209),
                            Order = 2,
                            Quesiton = "OS Type & Version",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -5,
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -33,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5213),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5217),
                            Order = 3,
                            Quesiton = "Total Storage of Server in (GB'S TB'S) & amp; Partitions",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -5,
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -34,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5221),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5224),
                            Order = 4,
                            Quesiton = "State of Server (Physical, Virtual, Hyper-Visor)",
                            ReplyType = "Text",
                            SurveyQuestionGroupID = -5,
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -35,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5228),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5232),
                            Note = "(e.g. Amazon AWS, Azure, On-Premise)",
                            Order = 0,
                            Quesiton = "Moving to Hosting Service Provider?",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -36,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5236),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5239),
                            Order = 2,
                            Quesiton = "Is there a SAN? (Yes or No)",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -37,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5243),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5246),
                            Note = "(e.g. P= Physical V=Virtual P-P, P-V, V-V, V-P)",
                            Order = 3,
                            Quesiton = "Specify the Type of Migration?",
                            ReplyType = "Text",
                            SurveyStepId = -3
                        },
                        new
                        {
                            Id = -38,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5250),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(5253),
                            Order = 4,
                            Quesiton = "Please include any additional technical details that you may feel is important that was not covered above:",
                            ReplyType = "TextArea",
                            SurveyStepId = -3
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SurveyStepId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyStepId");

                    b.ToTable("SurveyQuestionGroup");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(8303),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(8320),
                            Order = 1,
                            SurveyStepId = -2,
                            Title = "Specify the number of Source Server(s) to be migrated, Type, OS, Storage, State?"
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(9927),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(9949),
                            Note = "(e.g. Microsoft SQL 2014, MariaDB 5.6, MySQL 5.4, Name of DB, size of DB, MB’s, GB’s, TB’s)",
                            Order = 4,
                            SurveyStepId = -2,
                            Title = "Specify the Database Engine Server(s) Type | Version | Name | Size | Quantity?"
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(648),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(664),
                            Note = "(if Yes please List)",
                            Order = 10,
                            SurveyStepId = -2,
                            Title = "Are there any SSL certificate(s) installed (Type &amp; Location If possible)?"
                        },
                        new
                        {
                            Id = -4,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(687),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(690),
                            Order = 13,
                            SurveyStepId = -2,
                            Title = "List the number of Website Names (&amp; Location on Servers if possible)?"
                        },
                        new
                        {
                            Id = -5,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(695),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 236, DateTimeKind.Local).AddTicks(698),
                            Order = 1,
                            SurveyStepId = -3,
                            Title = "Specify the number of Source Server(s) to be migrated, Type, OS, Storage, State?"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyVersion")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId", "SurveyVersion");

                    b.ToTable("SurveyStep");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(896),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(919),
                            Order = 0,
                            SurveyId = -1,
                            SurveyVersion = 8,
                            Title = "Organization/Company &amp; Primary Contact Details: Step A"
                        },
                        new
                        {
                            Id = -2,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(3082),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(3099),
                            Order = 1,
                            SurveyId = -1,
                            SurveyVersion = 8,
                            Title = "Source Migration Infrastructure Details: Step B"
                        },
                        new
                        {
                            Id = -3,
                            CreatedBy = "Anonymous",
                            CreatedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(3142),
                            IsActive = true,
                            ModifiedBy = "Anonymous",
                            ModifiedDate = new DateTime(2020, 6, 17, 12, 38, 4, 235, DateTimeKind.Local).AddTicks(3145),
                            Order = 2,
                            SurveyId = -1,
                            SurveyVersion = 8,
                            Title = "Destination Migration Infrastructure Details: Step C"
                        });
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.ClientSurveys", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.Client", "Client")
                        .WithMany("ClientSurveys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Survey.Core.Data.Entities.Survey", "Survey")
                        .WithMany("ClientSurveys")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Content", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.StepContent", "StepContent")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("StepContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.Reply", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.ClientSurveys", "ClientSurvey")
                        .WithMany("ClientQuestionReplies")
                        .HasForeignKey("ClientSurveyId");

                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyQuestion", "SurveyQuestion")
                        .WithMany("PossibleReplies")
                        .HasForeignKey("SurveyQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.StepContent", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithOne("StepContent")
                        .HasForeignKey("Company.Survey.Core.Data.Entities.StepContent", "SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", "SurveyQuestionGroup")
                        .WithMany("SurveyGroupQuestions")
                        .HasForeignKey("SurveyQuestionGroupID");

                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyQuestionGroup", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.SurveyStep", "SurveyStep")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("SurveyStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.Survey.Core.Data.Entities.SurveyStep", b =>
                {
                    b.HasOne("Company.Survey.Core.Data.Entities.Survey", "Survey")
                        .WithMany("SurveySteps")
                        .HasForeignKey("SurveyId", "SurveyVersion")
                        .HasPrincipalKey("Id", "Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
